# Generated by Django 4.0.6 on 2022-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empty task', max_length=144)),
                ('deadline', models.DateTimeField()),
                ('task_type', models.CharField(max_length=66)),
            ],
        ),
    ]
